# Generated by Django 3.1.3 on 2020-12-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sector',
            field=models.PositiveSmallIntegerField(choices=[(1, 'secretaria'), (2, 'gerencia'), (3, 'ventas'), (4, 'taller'), ('profesional', 'profesionales')]),
        ),
    ]
