# Generated by Django 3.1.3 on 2020-12-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201201_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sector',
            field=models.PositiveSmallIntegerField(choices=[(1, 'secretaria'), (2, 'gerencia'), (3, 'ventas'), (4, 'taller'), (5, 'profesionales')]),
        ),
    ]
