# Generated by Django 3.1.3 on 2020-12-01 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201201_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('dni', models.IntegerField(unique=True)),
                ('asistencia', models.BooleanField(default=True)),
                ('historial_medico', models.TextField()),
                ('id_medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elmedico', to='user.profesional')),
                ('id_secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elsecreta', to='user.secretaria')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.DateTimeField(unique=True)),
                ('id_paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elpaciente', to='user.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('lente', models.BooleanField(default=False)),
                ('lejos', models.BooleanField(default=False)),
                ('cerca', models.BooleanField(default=False)),
                ('izquierda', models.BooleanField(default=False)),
                ('derecha', models.BooleanField(default=False)),
                ('armazon', models.BooleanField(default=False)),
                ('pendiente', models.BooleanField(default=True)),
                ('ventas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elventas', to='user.ventas')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientele', to='user.paciente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elproducto', to='user.producto')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eltaller', to='user.taller')),
            ],
        ),
    ]
