# Generated by Django 3.1.3 on 2020-12-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_paciente_pedido_producto_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sector',
            field=models.CharField(choices=[('secretaria', 'secretaria'), ('gerencia', 'gerencia'), ('ventas', 'ventas'), ('taller', 'taller'), ('profesionales', 'profesionales')], max_length=15),
        ),
    ]
